# Practical 3: Eigenvalues and Eigenvectors

### Eigenvalues & Eigenvectors of a Square Matrix

In [1]:
import numpy as np
# Define square matrix A
A = np.array([[2,0,1],[-1,4,-1],[-1,2,0]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)

[[ 2  0  1]
 [-1  4 -1]
 [-1  2  0]]
Eigenvalues are:  [3. 2. 1.]
Eigenvectors are:  [[ 4.08248290e-01  8.94427191e-01 -7.07106781e-01]
 [ 8.16496581e-01  4.47213595e-01 -8.72620868e-17]
 [ 4.08248290e-01 -4.12775854e-16  7.07106781e-01]]


In [2]:
import numpy as np 
C = np.array([[7,-1],[-1,4]])
eigvals, eigvecs = np.linalg.eig(C)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)
#First values of eigvals is lambda 1 and second value is lambda 2
#First column of eigvecs is v1 and second column is v2

Eigenvalues are:  [7.30277564 3.69722436]
Eigenvectors are:  [[ 0.95709203  0.28978415]
 [-0.28978415  0.95709203]]


So the eigenvalues of A are: 3, 2, and 1
Notice that the corresponding eigenvectors are given in columns and are 
normalized to unit length.

In [ ]:
# The first eigenvalue is 3
# Its corresponding eigenvector is in column 1 of eigvecs
print("First eigenvalue is: ", eigvals[0])# subject to rounding errors
print("Corresponding eigenvector is: ", eigvecs[:,0])
print("Its magnitude is: ", np.linalg.norm(eigvecs[:,0])) # subject to rounding error


To check whether the first vector and first value are indeed the eigenvector and eigenvalue
of A, we do the following:

In [ ]:
# Find Av
B = np.dot(A, eigvecs[:,0])
print("Av is: ", B)

# Find lambda*v
C = eigvals[0]* eigvecs[:,0]
print("lambda*v is: ", C)


Notice that the two answers are the same, confirming that the first vector is an eigenvector
corresponding to the first eigenvalue. 

### Task 1

Some properties of eigenvalues include:<br> 
•	The sum of eigenvalues of a matrix equals its trace.<br>
•	The product of eigenvalues equals its determinant.<br><br>
Verify the properties above using the matrix $\mathbf{A}=\begin{bmatrix}2 & 1 & 2 \\ 2 & 2 & -2 \\ 3 & 1 & 1 \end{bmatrix}$

In [ ]:
# Solution for Task 1.
import numpy as np

                 # Define matrix A
print(A)

In [ ]:
                      #Get eigenvalues & eigenvectors
print(eigvals)
print(A.trace())

Notice in the above that the sum of eigenvalues of A equals its trace

In [ ]:
print(np.linalg.det(A)) # find determinant

Notice also that the product of eigenvalues of A is its determinant

In [ ]:
# End of solution for Task 1.

### Task 2

**Dot Product**: The dot product of 2 vectors $\mathbf{u}=\begin{bmatrix}u_1\\ u_2 \\ \vdots \\ u_n\end{bmatrix}$ and $\mathbf{v}=\begin{bmatrix}v_1\\ v_2 \\ \vdots \\ v_n\end{bmatrix} $ is given by <br><br>
$$\mathbf{u}^T\mathbf{v}=u_1v_1+u_2v_2+\cdots+u_nv_n $$ <br>
When the dot product of 2 vectors is equal to zero, the vectors are said to be **orthogonal**.

**Symmetric Matrix**: The eigenvalues of a symmetrical matrix are always real and the eigenvectors for different eigenvalues are always orthogonal. Verify this in Python for the matrix A below.<br>
$$\mathbf{A}=\begin{bmatrix}1 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 1 \end{bmatrix}$$

In [ ]:
#Solution for Task 2. 
                      # Define matrix A
print(A)
                      # Get eigenvalues & eigenvectors
print(eigvals)

Notice that eigenvalues are 3,1,0, which are real numbers.

Now look at the eigenvectors:

In [ ]:
v1 = eigvecs[:,0]
v2 = eigvecs[:,1]
v3 = eigvecs[:,2]

We can find the dot product between **v1** and **v2**, and check whether it is zero.
Similarly for the pairs **v1** & **v3**, and **v2** & **v3**.

In [ ]:
print(np.dot(v1, v2))
print(np.dot(v1, v3))
print(np.dot(v3, v2))

The pairwise dot products are zero, verifying that the eigenvectors of the symmetric matrix A are orthogonal. This can be shown to be generally true for all symmetric matrices.

In [ ]:
# End of solution for Task 2