# Practical 1a: Matrices and Inverse Matrix Method


Many machine learning algorithms make use of matrices to store and process data. 
For example, a deep learning algorithm makes use of matrices to store inputs such as 
images, tweets, or text to solve problems. An artificial neural network makes use of 
matrices to store information such as weights during training. A familiarity with 
matrices/vectors is hence important.

In this practical we will learn some of the fundamentals of matrices/vectors and to use the 
inverse matrix method to solve systems of linear equations with unique solutions.

A **vector** can be represented as a list in Python.
For example:

In [4]:
v = [ 1, 4, 2]
print(v)

[1, 4, 2]


A **matrix** is a 2D array which stores numbers. 
Alternatively, a matrix can also be thought of as 
a list of vectors.

An example:

In [5]:
A = [[1,4,2],[0,6,3],[3,5,6]]
print(A)

[[1, 4, 2], [0, 6, 3], [3, 5, 6]]


An alternative way to work with vectors and matrices is
to use the **NumPy** module in Python.

In [6]:
import numpy as np
v = np.array([[1],
               [4],
               [2]])
print(v)
A = np.array([[1,4, 2], [0, 6, 3],[3, 5, 6]])
print(A)

[[1]
 [4]
 [2]]
[[1 4 2]
 [0 6 3]
 [3 5 6]]


We can check the order of **A** and **v** as follows:

In [7]:
print("A if of dimension: ", A.shape)
print("v is of dimension: ", v.shape)

A if of dimension:  (3, 3)
v is of dimension:  (3, 1)


We can check any element of **A** as follows:

In [8]:
print("The element of A in row 1 and column 2: ", A[0,1])

The element of A in row 1 and column 2:  4


There are a lot of matrix operations which we can make use
of in **NumPy**. Some examples are given below.

In [9]:
# Matrix Addition
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = A+B
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[ 8 10]
 [10  8]]


In [10]:
# Matrix Subtraction
D = A - B
print(D)

[[ 2  6]
 [ 2 10]]


In [11]:
# Matrix-Scalar Multiplication
A = np.array([[5,8],[6,9]])
print(A)
b = 2
E = A*2
print(E)

[[5 8]
 [6 9]]
[[10 16]
 [12 18]]


In [12]:
# Matrix-Vector Multiplication
A = np.array([[5,8],[6,9]])
print(A)
v = np.array([[1],[4]])
print(v)
w = np.dot(A,v)
print(w)
z = np.matmul(A,v)
print(z)

[[5 8]
 [6 9]]
[[1]
 [4]]
[[37]
 [42]]
[[37]
 [42]]


In [13]:
# Matrix-Matrix Multiplication
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = np.dot(A,B)
print(C)
D = np.matmul(A,B)
print(D)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[47  2]
 [54  3]]
[[47  2]
 [54  3]]


In [14]:
# Taking transpose
print(A)
B = A.T
print(B)

[[5 8]
 [6 9]]
[[5 6]
 [8 9]]


In [15]:
# Finding Matrix Determinant
A = np.array([[5,8],[6,9]])
print(A)
detA = np.linalg.det(A)
print(detA)

[[5 8]
 [6 9]]
-2.9999999999999982


In [16]:
# Matrix Inverse
print(A)
B = np.linalg.inv(A)
print(B)

[[5 8]
 [6 9]]
[[-3.          2.66666667]
 [ 2.         -1.66666667]]


An **identity matrix** of order 3 can be created as follows:

In [17]:
I3 = np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


To create a 2x3 matrix of random numbers drawn from a normal distribution with mean 0 and variance 1, we use:

In [18]:
weights = np.random.randn(2,3)
print(weights)

[[ 1.0142802  -0.15330032  0.84389782]
 [-1.69273687  0.04046349  0.21697742]]


A 3x3 **diagonal matrix** with (1, 5, 1) along its principal diagonal can be constructed as follows:

In [19]:
A = np.diag((1, 5, 1))
print(A)

[[1 0 0]
 [0 5 0]
 [0 0 1]]


To create a 1x3 matrix of **ones**, we can do as follows:

In [20]:
A = np.ones((1,3))
print(A)

[[1. 1. 1.]]


### Task 1
Determine if each of the following matrices is singular.<br>
(a) $\mathbf{A}=\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}0 & 1 & 3 & 4 \\ -2 & 1 & 2 & 1 \\ 2 & 0 & 1 & 0 \\ 0 & 8 & 3 & 1 \end{bmatrix}$ <br>

In [31]:
# (a)
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
detA = np.linalg.det(A)

print(detA)

-9.51619735392994e-16


In [33]:
# (b)
import numpy as np
A = np.array([[0,1,3,4],[-2,1,2,1],[2,0,1,0],[0,8,3,1]])
detA = np.linalg.det(A)

print(detA)



-126.0


### Task 2
Find the inverse of each matrix and verify that $\mathbf{A}\mathbf{A}^{-1}=\mathbf{A}^{-1}\mathbf{A}=\mathbf{I}$.<br>
(a) $\mathbf{A}=\begin{bmatrix}2 & 1 \\ 3 & 5 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}1 & 1 & 2 \\ 2 & 1 & 1 \\ 1 & 2 & 1 \end{bmatrix}$

In [34]:
# (a) find inverse
A = np.array([[2,1],[3,5]])
invA = np.linalg.inv(A)

print(invA)


[[ 0.71428571 -0.14285714]
 [-0.42857143  0.28571429]]


In [35]:
# (a) verify

D = np.matmul(A,invA)
print(D)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]


In [36]:
# (a) find inverse

A = np.array([[1,1,2],[2,1,1],[1,2,1]])
invA = np.linalg.inv(A)

print(invA)


[[-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]
 [ 0.75 -0.25 -0.25]]


In [37]:
# (b) verify

D = np.matmul(A,invA)
print(D)

[[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]


### Task 3
Solve the following system of linear equations.<br>

$$\begin{eqnarray}
w\ &+&  && y &+& z &=& 0 \\
2w\ &+& x &-& 2y &-& 3z &=& 3 \\
4w\ &-& 8x &-& y &+& 2z &=& 3 \\
-3w\ &+& 2x &+& y &+& 6z &=& 8 \\
\end{eqnarray}$$

In [41]:
# define A and b
# students to fill in

A = np.array([[1,0,1,1],[2,1,-2,-3],[4,-8,-1,2],[-3,2,1,6]])
B = np.array([[0],[3],[3],[8]])

print(A)
print(B)

[[ 1  0  1  1]
 [ 2  1 -2 -3]
 [ 4 -8 -1  2]
 [-3  2  1  6]]
[[0]
 [3]
 [3]
 [8]]


In [42]:
# find inverse of A

invA = np.linalg.inv(A)
print(invA)

[[ 0.47236181  0.23115578  0.03517588  0.02512563]
 [ 0.20603015  0.18592965 -0.08040201  0.08542714]
 [ 0.4321608  -0.34170854 -0.09547739 -0.21105528]
 [ 0.09547739  0.11055276  0.06030151  0.18592965]]


In [44]:
# solve for x

x = np.matmul(invA,B)
print(x)

[[ 1.]
 [ 1.]
 [-3.]
 [ 2.]]
